name: Build-Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build vsign
        run: |
          make cross
          mv vsign-windows-amd64 vsign-windows-amd64.exe
      - name: Upload artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            vsign-*
            vsign.-*sha256
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "vsign-*,vsign.-*sha256"
          bodyFile: "CHANGELOG.md"
           